#!/bin/bash

# Wrapper script for making sure commit message to `git` isn't greater than 50
# characters.

ARG=1
while [ $ARG -lt $# ] ; do
	if [ "${!ARG}" = "-m" ]; then
		ARG=`expr $ARG + 1`
		if [ `echo -n "${!ARG}" | wc -c` -gt 50 ]; then
			echo "Commit message cannot be more than 50 characters"
			exit 1
		fi
	fi
	ARG=`expr $ARG + 1`
done

exec /usr/bin/git "$@"
